#!/bin/bash

if [ "$1" == "--help" ] || [ -z "$1" ]; then
	echo "💈 $0 <quality> <input> <output> <chatter>"
	echo "  ➢ quality: 'fancy', 'mid', or 'potato' (obviously)"
	echo "  ➢ input: input glb file path (duh)"
	echo "  ➢ output: output path (do I have to spell everything out?)"
	echo "  ➢ chatter: 'inspect', 'silent', or omitted for basic info"
	exit 0
fi

quality=$1
input=$2
output=$3
chatter=$4

if [ -z "$quality" ]; then
	echo "error: quality must be provided. get some --help. can't you read instructions?"
	exit 1
fi

if [ -z "$input" ]; then
	echo "error: no input specified. what are you doing?"
	exit 1
fi

if [ -z "$output" ]; then
	echo "error: no output specified. get it together."
	exit 1
fi

cp $input $output

npx gltf-transform dedup \
	$output \
	$output \
	> /dev/null

case $quality in
	"fancy")
		if [ "$chatter" != "silent" ]; then
			echo "🧁 fancy quality. brace yourself for a fat file."
		fi

		npx gltf-transform resize \
			--width 1024 \
			--height 1024 \
			$output \
			$output \
			> /dev/null

		npx gltf-transform webp \
			--quality 80 \
			$output \
			$output \
			> /dev/null

		;;
	"mid")
		if [ "$chatter" != "silent" ]; then
			echo "🍏 mid quality. standard fare for standard people."
		fi

		npx gltf-transform resize \
			--width 512 \
			--height 512 \
			$output \
			$output \
			> /dev/null

		npx gltf-transform webp \
			--quality 60 \
			$output \
			$output \
			> /dev/null

		;;
	"potato")
		if [ "$chatter" != "silent" ]; then
			echo "🥔 potato quality. are you running this on a toaster?"
		fi

		npx gltf-transform quantize \
			--quantize-color 4 \
			--quantize-generic 8 \
			--quantize-normal 8 \
			--quantize-position 8 \
			--quantize-texcoord 8 \
			--quantize-weight 8 \
			$output \
			$output \
			> /dev/null

		npx gltf-transform resize \
			--width 128 \
			--height 128 \
			$output \
			$output \
			> /dev/null

		npx gltf-transform webp \
			--quality 10 \
			$output \
			$output \
			> /dev/null

		;;
	*)
		echo "invalid quality >:[ screw you"
		exit 1
		;;
esac

npx gltf-transform draco \
	$output \
	$output \
	> /dev/null

if [ "$chatter" == "inspect" ]; then
	npx gltf-transform inspect \
		$output
fi

if [ "$chatter" != "silent" ]; then
	echo "ℹ️ $(du -h "$output" | cut -f1)"
	echo "✅ $(realpath "$output")"
fi

